#!/bin/sh
set -e

# As root:
echo "Starting D-Bus daemon..."
dbus-daemon --system
echo "Starting Avahi daemon..."
avahi-daemon --no-chroot --daemonize

# Drop privileges to 'streamer'
su-exec streamer vidstream "$@"