#!/bin/bash
set -euo pipefail

if [ $# -eq 0 ]; then
  echo "Error: No video file provided."
  echo "Usage: vidstream <video-file>"
  exit 1
fi
videofile=$1
if [ ! -f "$videofile" ]; then
  echo "Error: File '$videofile' not found."
  exit 1
fi

echo "Starting GStreamer pipeline.."
echo ---------------------------------
echo $videofile
RECEIVER_IP=127.0.0.1

# GStreamer pipeline
gst-launch-1.0 filesrc location="$videofile" \
  ! decodebin \
  ! x264enc tune=zerolatency \
  ! rtph264pay config-interval=1 pt=96 \
  ! udpsink host=$RECEIVER_IP port=5000